 DROP DATABASE crm_system
 
DROP TABLE SALE_PRODUCTS
DROP TABLE SALES
DROP TABLE USERS
DROP TABLE PRODUCTS


DROP PROCEDURE IF EXISTS get_single_users;
DROP PROCEDURE IF EXISTS GetCustomers;
DROP PROCEDURE IF EXISTS GetEmployees;
DROP PROCEDURE IF EXISTS GetEmployeeUsers;
DROP PROCEDURE IF EXISTS UserLogin;
DROP PROCEDURE IF EXISTS GetProducts;
DROP PROCEDURE IF EXISTS GetSaleInformation;
DROP PROCEDURE IF EXISTS MakeSale;
DROP PROCEDURE IF EXISTS GetDailySales;
DROP PROCEDURE IF EXISTS get_new_users_today;
DROP PROCEDURE IF EXISTS GetDailyRefundedSalesProducts;
DROP PROCEDURE IF EXISTS AddNewEmployee;
DROP PROCEDURE IF EXISTS AddNewCustomer;
DROP PROCEDURE IF EXISTS AddCustomer;
DROP PROCEDURE IF EXISTS UpdateEmployee;
DROP PROCEDURE IF EXISTS UpdateCustomer
DROP PROCEDURE IF EXISTS GetProductById;
DROP PROCEDURE IF EXISTS GetEmployeeById;
DROP PROCEDURE IF EXISTS GetAllCategories;
DROP PROCEDURE IF EXISTS AddProduct;
DROP PROCEDURE IF EXISTS UpdateProduct;

