###
GET http://localhost:5000/users/employees
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXBsZS5jb20iLCJpYXQiOjE2Nzk5NTcwODUsImV4cCI6MTY3OTk3ODY4NX0.4edoPsu7Jf6Iu_CXLWTjcWlsWc7yxkz1KkBJobI9ALE
###
GET http://localhost:5000/users/71E8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXBsZS5jb20iLCJpYXQiOjE2Nzk5NTcwODUsImV4cCI6MTY3OTk3ODY4NX0.4edoPsu7Jf6Iu_CXLWTjcWlsWc7yxkz1KkBJobI9ALE

###
GET http://localhost:5000/users/customers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXBsZS5jb20iLCJpYXQiOjE2Nzk5NTcwODUsImV4cCI6MTY3OTk3ODY4NX0.4edoPsu7Jf6Iu_CXLWTjcWlsWc7yxkz1KkBJobI9ALE
###
POST http://localhost:5000/users/addcustomer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXBsZS5jb20iLCJpYXQiOjE2Nzk5NTcwODUsImV4cCI6MTY3OTk3ODY4NX0.4edoPsu7Jf6Iu_CXLWTjcWlsWc7yxkz1KkBJobI9ALE

{
  "email": "gemmatiru@gmail.com",
  "gender": "male",
  "role": "customer",
  "phone_number": "+2468013579",
  "name": "GEM matiru"
}

###

POST http://localhost:5000/users/addemployee
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXBsZS5jb20iLCJpYXQiOjE2Nzk5NTcwODUsImV4cCI6MTY3OTk3ODY4NX0.4edoPsu7Jf6Iu_CXLWTjcWlsWc7yxkz1KkBJobI9ALE

{
  "email": "jesssie@eple.com",
  "role": "superAdmin",
  "gender": "female",
  "password": "password123",
  "phone_number": "+1234589011",
  "name": "Jessie Me"
}
















###
POST  http://localhost:5000/users/login
Content-Type: application/json


{
    "email":"jesssie@eple.com",
    "password":"password123"


}
###

 PUT http://localhost:5000/users/editcustomer/71E8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXBsZS5jb20iLCJpYXQiOjE2Nzk5NTcwODUsImV4cCI6MTY3OTk3ODY4NX0.4edoPsu7Jf6Iu_CXLWTjcWlsWc7yxkz1KkBJobI9ALE


{
  "email": "gemmatiru1@gmail.com",
  "phone_number": "+11234567890",
  "name": "gem kagwa"
  
  
}


###
PUT http://localhost:5000/users/editemployee/D26A
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXBsZS5jb20iLCJpYXQiOjE2Nzk5NTcwODUsImV4cCI6MTY3OTk3ODY4NX0.4edoPsu7Jf6Iu_CXLWTjcWlsWc7yxkz1KkBJobI9ALE


{
  
  "phone_number": " 11234567890",
  "name": "Jessie Girl",
  "password": "newpassword",
  "image_link": "https://example.com/image.jpg"
}






